#!/bin/sh
#if [ $# = 0 ]; then
#    echo "copy executable file to destination directory"
#    echo "Usage: fcpex [destination_path]"
#    exit
#fi

if [ $# = 0 ]; then
    echo "copying executable to ~/tmp"
    find . -executable -type f -exec cp -rfpv {} ~/tmp \;
elif [ $# = 1 ]; then
    echo "copying executable to $1"
    find . -executable -type f -exec cp -rfpv {} $1 \;
fi
