#!/usr/bin/env bash

PLATFORM='unknown'
UNAMESTR=$(uname)

if [ "$UNAMESTR" = "Linux" ]; then
    PLATFORM="linux"
elif [ "$UNAMESTR" = "Darwin" ]; then
    PLATFORM="mac"
else
    PLATFORM="windows"
fi

if [ "$PLATFORM" = "mac" ]; then
    client=/Applications/Emacs.app/Contents/MacOS/bin/emacsclient
else
    client=/usr/local/bin/emacsclient
fi

# check if any frame open
$client -n -e "(if (> (length (frame-list)) 1) 't)" 2>/dev/null | grep t &> /dev/null

if [ "$?" -eq "1" ]; then
    $client -nqc "$@" &> /dev/null
else
    $client -nq "$@" &> /dev/null
fi
