#!/usr/bin/env bash

client=/Applications/Emacs.app/Contents/MacOS/bin/emacsclient

# check if any frame open
$client -n -e "(if (> (length (frame-list)) 1) 't)" 2>/dev/null | grep t &> /dev/null

if [ "$?" -eq "1" ]; then
    $client -nqc "$@" &> /dev/null
else
    $client -nq "$@" &> /dev/null
fi
