#!/usr/bin/env ruby

require "resolv"

dns = Resolv::DNS.new(nameserver: ["8.8.8.8", "8.8.4.4"])

lists = ARGV

# convert domain name into ip if exist, otherwise, list current computer ip
if lists.empty?
  platform = RUBY_PLATFORM.downcase
  output = `#{(platform =~ /win32/) ? "ipconfig /all" : "ifconfig"}`
  case platform
  when /darwin/
    puts "output: #{output}"
    $1 if output =~ /en1.*?(([A-F0-9]{2}:){5}[A-F0-9]{2})/im
  when /win32/
    $1 if output =~ /Physical Address.*?(([A-F0-9]{2}-){5}[A-F0-9]{2})/im
  else
    nil
  end
else
  lists.each do |name|
    puts "#{name} => #{dns.getaddress(name)}"
  end
end
