#!/usr/bin/env node

const fetch = require('node-fetch');

const redmineUrl = 'http://192.168.100.12';
const apiKey = 'a94b5d457d5fb86efb6bda9e92f0ac3e6872baee';
const [node, program, ...issues] = process.argv;
const issueUrl = id => `${redmineUrl}/issues/${id}.json?key=${apiKey}`;
const issuesUrl = `${redmineUrl}/issues.json`;
const template = issue => `${issue.subject} [#${issue.id}](${redmineUrl}/issues/${issue.id})`;
const searchMe = !issues.length;

// copy content to system clipboard
const copyToClipboard = data => {
  const proc = require('child_process').spawn('pbcopy');
  proc.stdin.write(data);
  proc.stdin.end();
};

const results = [];

if (searchMe) {
  // list my tasks
  const query = `?key=${apiKey}&assigned_to_id=me&sort=updated_on:desc&limit=25&status_id=*`;
  
  const generateYesterday = date => {
    const year = date.getFullYear();
    const month = date.getMonth() + 1;
    const day = date.getDate() - 1;
    return `${year}-${month <= 9 ? '0' + month : month}-${day}`;
  };
  
  fetch(`${issuesUrl}${query}`)
    .then(response => response.json())
    .then(body => {
      const issues = body.issues;
      const date = new Date();
      const yesterday = generateYesterday(date);
      console.log(`[my tasks updated on ${yesterday}]`);
      const updatedYesterdayIssues = issues.filter(issue => issue.updated_on.includes(yesterday));
      updatedYesterdayIssues.forEach(issue => results.push('  ' + template(issue)));
    })
    .then(() => {
      const text = results.join('\n');
      console.log(text);
      copyToClipboard(text);
    });
} else {
  // list specified issues
  var calls = [];

  issues.forEach(id => calls.push(
    fetch(issueUrl(id))
      .then(response => response.json())
      .then(body => body.issue))
  );

  Promise.all(calls)
    .then(body => {
      console.log('[issues]');
      body.forEach(issue => {
        const content = template(issue);
        const line = '   ' + content;
        results.push(line);
      });
    })
    .then(() => {
      const text = results.join('\n');
      console.log(text);
      copyToClipboard(text);
    });
}
