#!/usr/bin/env node
// list all dsl jobs that is currently fail

require ('shelljs/global');
var request = require('request');
var htmlParser = require('htmlparser2');

var parser = new htmlParser.Parser({
  onopentag: function(name, attribs){
    // success job class name: job-status-blue
    // fail job class name: job-status-red
    if(name === "tr" && attribs.id && attribs.class && attribs.class.match(/red/)){
      console.log(attribs.id.replace('job_', ''));
    }
  },
}, {decodeEntities: true});

var user = 'devadm';
var password = 'just4devadm';
var serverUrl = 'http://192.168.101.104:8080/';
var path = 'view/DSL Job Status';

request
  .get(serverUrl + path)
  .on('response', (res) => {
    res.setEncoding('utf8');
  })
  .on('data', (data) => {
    parser.write(data);
    parser.end();
  });
