#!/usr/bin/env bash
set -e

config_dir="${HOME}/.config"
recorderd_dir="${config_dir}/recorderd"

# create data directory if not exist

if [ ! -d "${config_dir}" ] || [ ! -d "${config_dir}/recorderd" ]; then
    mkdir -p "${config_dir}/recorderd"
fi

# enter recorderd directory
cd "${recorderd_dir}"

recorderd --config-file=recorderd.conf start

# return original directory
cd - 1
